version: '3.8'

services:
  crypto_bot:
    image: rvenz/crypto-tg-bot:latest
    container_name: crypto-tg-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # Сервис для очистки логов (запускается по требованию)
  cleanup_logs:
    build: .
    container_name: crypto-bot-cleanup
    command: ["python", "cleanup_logs.py"]
    volumes:
      - ./logs:/app/logs
    profiles:
      - cleanup